config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :feedbacks
  resources :posts
  root to: "pages#home"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/feedback.rb
class Feedback < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/feedbacks_controller.rb
class FeedbacksController < ApplicationController
  def index
    @feedbacks = Feedback.all
  end

  def show
    @feedback = Feedback.find(params[:id])
  end

  def new
  end

  def edit
  end

  def create
  end

  def update
  end

  def destroy
    @feedback = Feedback.find(params[:id])
    @feedback.destroy
    redirect_to feedback_url
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/feedbacks_helper.rb
module FeedbacksHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/feedbacks/create.html.erb
<h1>Feedbacks#create</h1>
<p>Find me in app/views/feedbacks/create.html.erb</p>

app/views/feedbacks/destroy.html.erb
<h1>Feedbacks#destroy</h1>
<p>Find me in app/views/feedbacks/destroy.html.erb</p>

app/views/feedbacks/edit.html.erb
<h1>Feedbacks#edit</h1>
<p>Find me in app/views/feedbacks/edit.html.erb</p>

app/views/feedbacks/index.html.erb
<h1>Feedbacks</h1>
<%= link_to "Criar feedback",new_feedback_path%>
<table class="table text-light">
 <thead>
  <tr>
   <th>nome</th>
   <th>desc</th>
   <th>data</th>
   <th>resolvido</th>
   <th>usuario</th>
   <th colspan="3"></th>
  <tr>
 <thead>
 <tbody data-target="feedbacks.row" data-action="click->feedback#show">
   <% @feedbacks.each do |feedback| %>
    <tr>
      <td><%= feedback.nome %></td>
      <td><%= feedback.desc %></td>
      <td><%= feedback.data%></td>
      <td><%= feedback.resolvido%></td>
      <td><%= feedback.usuario%></td>
      <td><%= link_to "Mostrar",feedback%></td>
      <td><%= link_to "Editar",edit_feedback_path(feedback)%></td>
      <td><%= button_to "Deletar",feedback,method: :delete%></td>
   <% end %>
 </tbody>
</table>

app/views/feedbacks/new.html.erb
<h1>Crie seu feedback</h1>
<%= form_with model: @feedback,data: {type: :hotwire} do |form| %>
 <div>
  <%= form.label :nome%>
  <%= form.text_field :nome%>
 </div>
 <div class="field">
  <%= form.label :desc%>
  <%= form.text_field :desc%>
 </div>
 <div class="field">
  <%= form.label :data%>
  <%= form.datetime_local_field :data%>
 </div>
 <div class="field">
  <%= form.label :resolvido%>
  <%= form.text_field :resolvido%>
 </div>
 <div class="field">
  <%= form.label :usuario%>
  <%= form.text_field :usuario%>
 </div>
<% end %>
<%=link_to "voltar", feedbacks_path%>

app/views/feedbacks/show.html.erb
<h1>Mostrando o feedback</h1>
<h2><%= @feedback.nome %></h2>
<p><%= @feedback.desc %></p>
<p><%= @feedback.data%></p>
<p><%= @feedback.resolvido%></p>
<p><%= @feedback.usuario%></p>
<%=link_to "voltar",feedbacks_path%>

app/views/feedbacks/update.html.erb
<h1>Feedbacks#update</h1>
<p>Find me in app/views/feedbacks/update.html.erb</p>

app/views/layouts/_navbar.html.erb
<nav class="navbar-geral navbar navbar-expand-lg">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <%= link_to "Home ",root_path,class: "navbar-brand"%>
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Feedbacks",feedbacks_path,class: "nav-link active"%>
        </li>
        
        
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HotrailsJoaoVitor</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "navbar", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <%= render "layouts/navbar"%>

    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>
<% if current_user %>
    <p> Bem Vindo <%= current_user.email %>!</p>
    <p> você é um <%= current_user.role %></p>
    <p> texto grande </p>
    <%= link_to "Sair",destroy_user_session_path,'data-turbo-method': :delete,class: "btn btn-danger"%>
<% else %>
    <p> voce n esta logado, faça o favor de logar vagabundo</p>
    <%= link_to "Logar", new_user_session_path,class: "btn btn-primary"%>
    <%= link_to "Crie sua conta", new_user_registration_path,class: "btn btn-success"%>
<% end %>